### ISSUE TITLE
[Bug report] jdbc-mysql catalogs failed on mysql 8.x driver

### ISSUE THREAD

**Issue by kalencaya** [datastrato/gravitino#3269]
### Version

main branch

### Describe what's wrong

 jdbc-mysql catalogs failed on mysql 8.x driver, but 5.x works well

### Error message and/or stacktrace

![error](https://github.com/datastrato/gravitino/assets/24804318/7e44926b-dc65-4a02-a2a0-bfee82ca72e3)

### How to reproduce

mount mysql 8.x driver to gravitino docker container on /root/gravitino/catalogs/jdbc-mysql/libs/mysql.jar and create jdbc-mysql catalog on gravitino ui

**Comment by yuqi1129** [comment]
> @FANNG1 @yuqi1129 would you please help to check this?

Got it, I will verify it today.

**Comment by yuqi1129** [comment]
@kalencaya 
Can you provide more details about it, we have used `mysql-connector-java-8.0.27.jar` for some time and it seems that nothing goes wrong, what is the version of jdbc-driver you use?

**Comment by kalencaya** [comment]
docker-compose.yml and jdbc properties
```
driver-class-name: com.mysql.cj.jdbc.Driver
jdbc-url: jdbc:mysql://mysql:3306/test
username: root
password: 123456
```


```
version: "3.8"

services:

  mysql:
    image: bitnami/mysql:8.0
    container_name: mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
      - MYSQL_DATABASE=test
    ports:
      - 3306:3306
    networks:
      - test

  gravitino:
    image: datastrato/gravitino:0.5.0
    container_name: gravitino
    ports:
      - 8090:8090
    restart: unless-stopped
    volumes:
      - ./mysql-connector-java-8.0.11.jar:/root/gravitino/catalogs/jdbc-mysql/libs/mysql.jar
    networks:
      - test

networks:
  test:
    driver: bridge

```
